import React, { createContext, useContext, useMemo, type ReactNode } from "react";

// ─────────────────────────────────────────────────────────────────────────────
// ZK Config Provider
//
// Uses FetchZkConfigProvider to load prover/verifier keys from static files
// served under /contract/alpha_vault/.
//
// NEVER use NodeZkConfigProvider here — it reads from the filesystem and
// only works in Node.js server contexts.
// ─────────────────────────────────────────────────────────────────────────────

interface ZkConfigContextValue {
  /** Base URL where compiled contract ZK artifacts are served */
  zkArtifactsBaseUrl: string;
  /**
   * Returns the URL for a named ZK artifact.
   * Artifacts are placed at /contract/alpha_vault/<name>
   */
  getArtifactUrl: (name: string) => string;
}

const ZkConfigContext = createContext<ZkConfigContextValue | null>(null);

interface ZkConfigProviderProps {
  children: ReactNode;
  /**
   * Base URL for ZK artifacts. Defaults to the Vite public folder path.
   * Override via VITE_ZK_ARTIFACTS_URL env var.
   */
  baseUrl?: string;
}

export function ZkConfigProvider({ children, baseUrl }: ZkConfigProviderProps) {
  const zkArtifactsBaseUrl =
    baseUrl ??
    (import.meta.env.VITE_ZK_ARTIFACTS_URL as string | undefined) ??
    "/contract/alpha_vault";

  const getArtifactUrl = useMemo(
    () => (name: string) => `${zkArtifactsBaseUrl}/${name}`,
    [zkArtifactsBaseUrl]
  );

  const value = useMemo(
    () => ({ zkArtifactsBaseUrl, getArtifactUrl }),
    [zkArtifactsBaseUrl, getArtifactUrl]
  );

  return (
    <ZkConfigContext.Provider value={value}>
      {children}
    </ZkConfigContext.Provider>
  );
}

export function useZkConfig(): ZkConfigContextValue {
  const ctx = useContext(ZkConfigContext);
  if (!ctx) {
    throw new Error("useZkConfig must be used within <ZkConfigProvider>");
  }
  return ctx;
}

/**
 * Build a FetchZkConfigProvider-compatible config object pointing to
 * statically-served ZK artifacts. Pass this into deployContract or
 * findDeployedContract from @midnight-ntwrk/midnight-js-contracts.
 *
 * Usage:
 *   const zkConfig = buildFetchZkConfig('/contract/alpha_vault');
 *   await deployContract(providers, { ...zkConfig });
 */
export function buildFetchZkConfig(baseUrl: string) {
  return {
    zkConfigProvider: {
      // FetchZkConfigProvider fetches verifier/prover key files via HTTP
      // These files are generated by `compact compile` and copied via
      // scripts/copy-artifacts.sh into frontend/public/contract/alpha_vault/
      proverKey: `${baseUrl}/alpha_vault.prover`,
      verifierKey: `${baseUrl}/alpha_vault.verifier`,
      contractWasm: `${baseUrl}/alpha_vault_bg.wasm`,
      contractJs: `${baseUrl}/alpha_vault.js`,
    },
  };
}
